name: Deploy to Scaleway Functions
author: Voorhoede
description: Use this action to deploy to Scaleway Functions

inputs:
   scw_secret_key:
    description: The secret key for your Scaleway account
    required: true
   scw_project_id:
    description: The id of the Scaleway project
    required: true

runs:
  using: "node20"
  main: ".lib-action/index.js"

branding:
  color: purple
  icon: upload-cloud
